#!/bin/bash

set -ex

sudo add-apt-repository --yes ppa:juju/stable
sudo apt-get update --yes
sudo apt-get install --yes python-amulet \
                           python-neutronclient \
                           python-keystoneclient \
                           python-novaclient \
                           python-glanceclient
