#!/usr/bin/python

"""Amulet tests on a basic ceilometer deployment on vivid-kilo."""

from basic_deployment import CeilometerBasicDeployment

if __name__ == '__main__':
    deployment = CeilometerBasicDeployment(series='vivid')
    deployment.run_tests()
